refactor: update commit-message-check.yml

diff --git a/.github/workflows/commit-message-check.yml b/.github/workflows/commit-message-check.yml
--- a/.github/workflows/commit-message-check.yml
+++ b/.github/workflows/commit-message-check.yml
@@ -13,7 +13,7 @@ jobs:
         uses: gsactions/commit-message-checker@v1
         with:
           pattern: "^(feat|chore|test|fix|perf|doc|refactor):"
-          error: 'Commit message does not start with "feat:", "chore:", "test:", "fix:", "perf:", "doc:", or "refactor"'
+          error: 'Commit message does not start with "feat:", "chore:", "test:", "fix:", "perf:", "doc:", or "refactor:"'
 
       - name: Check Commit Message Length
         run: |
@@ -26,4 +26,41 @@ jobs:
             echo "Actual length: $actual_length"
             echo "Required length: $min_length"
             exit 1
+          fi
+New
+
+
+olusola alao
+:headphones:  3:18 PM
+name: Commit Message Check
+
+on:
+  pull_request:
+    types: [opened, synchronize, reopened]
+
+jobs:
+  check-commit-message:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Check Commit Message
+        uses: gsactions/commit-message-checker@v1
+        with:
+          pattern: "^(feat|chore|test|fix|perf|doc|refactor):"
+          error: 'Commit message does not start with "feat:", "chore:", "test:", "fix:", "perf:", "doc:", or "refactor:"'
+
+      - name: Check Commit Message Length
+        run: |
+          commit_message=$(git log -1 --pretty=%B)
+          min_length=15
+          actual_length=${#commit_message}
+          if [ $actual_length -lt $min_length ]; then
+            echo "Commit message is too short. It must be at least $min_length characters."
+            echo "Actual message: '$commit_message'"
+            echo "Actual length: $actual_length"
+            echo "Required length: $min_length"
+            exit 1
+          fi
           fi
